sudo: required

services:
  - docker

language: go
go:
  - tip

env:
  global:
    - MYAPP=archive
    - MYEMAIL=mh-cbon@users.noreply.github.com
    - secure: SLWDRVatggJRYhXH3g22h9pGH1GyUCblzZu3MXg/BSaAZiDeH7bFeFLAUnJwV6BBMOBljOeSYKYHhzdM/p6BAd9A9Yr2qGOhiJbHOmwt7aB3500oYnMsgNqb3XglaeNHI211floSXv9I4DPbrzM1aUMX9tJOldsn0cZw0FC+pDKS2k7OWzGaKk4H4MPEM0YaB2PPi7fbnIPJEEK9EWXSQJOHfQkN+PHjUeGXE5DbRwCo9UDIDByUNlPWx8KMPCDPvl/4E3eibTTNrVf6SKBFjkBrLIuG3ae8h+n1XoPcz2zRHjOBiUehFVVgjOOWkClc78E4Unntdj0IjlZmhS7E3rWRZCS+ChKxoyPz10RMTTOpnJUVWKqlk2KfEVkWb0nV81J3BrNP3ZBXwfCClMeIuavM8AInjxl3xWjpnf6Rq+p8Hxx3wIp0IzX+eYTD2XdZG3Lh1gh0n/OkiwLD+RfrafCEvCYDfrzrep9l97epkaTV0kY9KrPKAU7ugzkbYNTZzDQGBj4m1fCzeD/QmyhkjWE74AiwzZ4Zf45oEro92Oeya1DTeJcC6RD6AsuRResjakTOcxlGZHYXqjoSKtx8sLSeXmXGM1zcobg0b0uaEIIPB72yfSqjIwZnoyIwNk0qobxUY8tOiEvjDndTebvHeW3JeN/lKRhcMb8h9G3UwK4=

before_install:
  - sudo apt-get -qq update
  - mkdir -p ${GOPATH}/bin
  - cd ~
  - curl https://glide.sh/get | sh

install:
  - cd $GOPATH/src/github.com/mh-cbon/$MYAPP
  - glide install
  - go install

script: echo "pass"

before_deploy:
  - mkdir -p build/{386,amd64}
  - mkdir -p pkg-build/{386,amd64}
  - GOOS=linux GOARCH=386 go build --ldflags "-X main.VERSION=${TRAVIS_TAG}" -o build/386/$MYAPP main.go
  - GOOS=linux GOARCH=amd64 go build --ldflags "-X main.VERSION=${TRAVIS_TAG}" -o build/amd64/$MYAPP main.go
  - curl -L https://raw.githubusercontent.com/mh-cbon/go-bin-deb/master/create-pkg.sh | GH=mh-cbon/$MYAPP sh -xe
  - curl -L https://raw.githubusercontent.com/mh-cbon/go-bin-rpm/master/create-pkg.sh | GH=mh-cbon/$MYAPP sh -xe

after_deploy:
  - curl -L https://raw.githubusercontent.com/mh-cbon/go-bin-deb/master/setup-repository.sh | GH=mh-cbon/$MYAPP EMAIL=$MYEMAIL sh -xe
  - curl -L https://raw.githubusercontent.com/mh-cbon/go-bin-rpm/master/setup-repository.sh | GH=mh-cbon/$MYAPP EMAIL=$MYEMAIL sh -xe

deploy:
  provider: releases
  api_key:
    secure: hK0IDXrVsDJGzTH6vVm6/FCK7t9lKo2IZLcUvi8BxijheSeTKO6uvcZgGDniJkQSZceDqMQ7c9LuxOjUE6zXjgR9dGmPp09W4R/CNcF0LNUQ7RIzJkUWBaKby383EHa/B08saJIjtbWZffQ2qOLSnZ05oYq5Os1uS+HsufBQTm9R9+x+2ydp66L6qy6YkFm7FnajixXlHyU/GjTg3ifOAZiiqDVfC1/gPR3RgMiGzdcrJmobtu+9W1ttdJqTnxFnmawA0pUT7/M3Cw7x2alD+yjpAlkZuftfTwwBR3TpDvnVyLry1foeb8xNH9FKhP0If2n4cjIPWrZgD7HiGo0JsljzCP24oIyFplda8v6xJCmzaR7hZiEOD7OAAE94YTESg8XGweN0PCdsPEBZ0vGHsb0/yVysKp6c2G2MBrTdnGOcgajpPaVnGkgaTRM4PwtKpFgyUI7VDhxCjBOvbgj18eZJssstAaXZjHD8kiDm/03B2Xs+FqT4lkCuTK4htWdD3/J7ABhvY8SqMLlEivt1nHhSPVRaox4pmktSaSwHndelZu1tVRV8g1zYP6liFSTCjQS3lqONRaPI2AHTjZaFsoXgk/gglSrCVZNK0+awEPz8dDU32iyqKta1uERtQJKuEBESwFOnSHq3RCfoH8LqaYoLVEw/DaNZl3hjVQi6JzQ=
  file_glob: true
  file:
    - $MYAPP-386.deb
    - $MYAPP-amd64.deb
    - $MYAPP-386.rpm
    - $MYAPP-amd64.rpm
  skip_cleanup: true
  on:
    tags: true
